name: news_repository
description: Dart package which manages the news domain.
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:  
  equatable: ^2.0.0
  uuid: ^3.0.0
  retrofit_generator: 3.0.1+1
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
  flutter_lints: ^1.0.0

dependencies:
  dio: ^4.0.4
  retrofit: ^3.0.1
  logger: ^1.1.0